<?php

/*
 * Intelli DB configs
 */
return [
    'openAiApiKey' => env('OPEN_AI_KEY'),
    'model' => env('OPEN_AI_MODEL', 'gpt-3.5-turbo'),

    /*
    |--------------------------------------------------------------------------
    | OpenAI model temperature
    |--------------------------------------------------------------------------
    |
    | Temperature is a parameter that controls the “creativity” or randomness
    | of the text generated by GPT-3. A higher temperature (e.g., 0.7) results
    | in more diverse and creative output, while a lower temperature (e.g., 0.2)
    | makes the output more deterministic and focused.
    |
    */
    'temperature' => 0.7,

    /*
    |--------------------------------------------------------------------------
    | OpenAI Frequency_penalty
    |--------------------------------------------------------------------------
    |
    | This parameter is used to discourage the model from repeating the same
    | words or phrases too frequently within the generated text.
    |
    */
    'frequency_penalty' => 0,
];
